---
# Per-Computer (gitignored '.\config.yml') Configuration File as used by all scripts in this folder

applications_update: false
allow_reboot: true
exit_anyways_if_reboot_required: false

wsl_install: false
wsl_distro: Ubuntu-20.04

setup_gpg: true
gpg_email: opensource@jonaspammer.at
# may use "{{ gpg_email }}"" placeholder
gpg_1password_pk_item_name: "PGP/GnuGPG private key {{ gpg_email }}" # pragma: allowlist secret
# may use "{{ gpg_email }}"" placeholder
gpg_1password_passphrase_item_name: "PGP/GnuGPG Passphrase {{ gpg_email }}" # pragma: allowlist secret
