---
# Per-Computer (gitignored '.\config.yml') Configuration File as used by all scripts in this folder

applications_update: false
allow_reboot: true
exit_anyways_if_reboot_required: false

wsl_install: false
wsl_distro: Ubuntu-20.04

setup_gpg: true
gpg_email: opensource@jonaspammer.at
# may use "{{ gpg_email }}"" placeholder
gpg_1password_item_name: "PGP/GnuGPG {{ gpg_email }}" # pragma: allowlist secret

setup_ssh: true
ssh_name: "BOESER-DRACHE-3"
# may use "{{ ssh_name }}"" placeholder
ssh_1password_item_name: "SSH Key {{ ssh_name}}"
