---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for a list of all hooks
repos:
  ### GENERAL ###
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-json
        exclude: ".devcontainer/devcontainer.json"
      - id: check-toml
      - id: check-xml
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        exclude: |
          (?x)^(
              .cruft.json|
          )$

  # opinionated code formatter for all things frontend (also includes Markdown, JSON, YAML)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

default_language_version:
  python: python3
ci:
  skip: []
  autofix_commit_msg: |
    chore(pre-commit): auto fixes from hooks :rotating_light:

    for more information, see https://pre-commit.ci
  autoupdate_commit_msg: |
    chore(pre-commit): autoupdate :arrow_up:

    TIP: you can trigger a re-run on a pull request by commenting `pre-commit.ci run` (must appear on a line by itself)
exclude: ".idea"
