= 👋 Hey there. My name's Jonas
// https://tryhackme.com/p/PixelTutorials[image:https://img.shields.io/badge/TryHackMe-004daa?logo=tryhackme&logoColor=white[tryhackme]]

link:Diagram.drawio.png[image:https://img.shields.io/badge/Home%20Setup%20Diagram-df6c0c?style=for-the-badge&logo=diagrams.net&logoColor=black[Home Setup Diagram]]
link:SETUP.adoc[image:https://img.shields.io/badge/PC%20Setup-lightblue?style=for-the-badge&logo=googlehome&logoSize=auto[PC Setup]]

// Already shown in GitHub Sidebar. If wanted, badge it:
// image:https://img.shields.io/badge/Location-EU%2C%20Austria%2C%20Vorarlberg%20(CET%20%2B1%20hour)-blue?style=for-the-badge&logo=googlemaps&logoSize=auto[Static Badge]
//📍__**Location**__ EU, Austria, Vorarlberg (CET +1 hour)

📺 Favourite Series::
Avatar: The Last Airbender, Star Trek (VOY / TNG / PICARD / DISCOVERY)

⛳ Hobbies and Interests::
Furry Community, Watching Movies with Friends, Teaching, Programming, Keeping home setup organized

I know my way around https://www.linkedin.com/in/jonas-pammer-2b340a1aa[IT ^image:https://img.shields.io/badge/LinkedIn-darkblue?style=social&logo=biolink[LinkedIn]^],
the https://stackshare.io/JonasPammer/my-stack[full stack around programming ^image:https://img.shields.io/badge/stackshare-lightblue?logo=stackshare[stackshare]^]
and generally like to always try to understand most of the things I stumble across every day.

// .👨‍💻 Some Yapping about DevOps and Unix-Epoch
// [%collapsible]
// ====
// link:JOURNEY.adoc[🛝 My Journey, for the Interested]

// DevOps - the modern take on "Full Stack Developer" - is a very fascinating topic
// that is fundamentally changing the way software development and deployment is https://landscape.cncf.io/[done].
// Servers and virtual machines are no longer seen as untouchable black boxes, but as implicitly documented, disposable on-demand creations.
// It's truly the pinnacle of automation and reproducibility!

// And the crazy thing is that **nothing has fundamentally changed** -
// It's just that The solutions like Linux, SSH, HTTP, TLS, TCP/IP, and more were created by brilliant minds long ago, and they're so ingeniously designed
// that we're still continue to stick them together in order to build the next big thing. IT is amazing.
// ====

// link:demystifying/module_bundlers.adoc[JavaScript Module Bundlers] 	-
// link:demystifying/transpilers.adoc[JavaScript Transpilers]	-
// link:demystifying/linters_and_formatters.adoc[Linters and Formatters]	-
// link:demystifying/conventional_commits.adoc[Conventional Commits]


== 🔝 Current Primary Fascination::
Fancy Library-Packed CookieCutter-Django with HTMX, Grails/Geb

// Programming Languages
image:https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=fff&style=for-the-badge[Python]
image:https://img.shields.io/badge/TypeScript-3178C6?logo=typescript&logoColor=fff&style=for-the-badge[TypeScript]
image:https://img.shields.io/badge/Groovy_Java-%23619DBD.svg?logo=openjdk&logoColor=white&style=for-the-badge[Java]
// Frameworks & Libraries
image:https://img.shields.io/badge/Django_HTMX-092E20?logo=django&logoColor=white&style=for-the-badge[Django]
image:https://img.shields.io/badge/jQuery-0769AD?logo=jquery&logoColor=fff&style=for-the-badge[jQuery]
image:https://img.shields.io/badge/Bootstrap_5-7952B3?logo=bootstrap&logoColor=white&style=for-the-badge[Bootstrap]
// DevOps & Tools
image:https://img.shields.io/badge/GitHub-%23121011.svg?logo=github&logoColor=white&style=for-the-badge[GitHub]
image:https://img.shields.io/badge/GitLab_CI-df6c0c?logo=gitlab&logoColor=white&style=for-the-badge[GitLab CI]
image:https://img.shields.io/badge/GitHub_Actions-2088FF?logo=github-actions&logoColor=white&style=for-the-badge[GitHub Actions]
image:https://img.shields.io/badge/Ansible-black?logo=ansible&logoColor=white&style=for-the-badge[Ansible]

🙋‍♂️ I https://github.com/JonasPammer?tab=stars[actively star repositories I find useful and interesting]::
Below is an automatically generated overview of my GitHub profile, showing mostly my recently starred projects (which may give somewhat of an indication of what I'm currently onto):

image::./github-metrics.svg[Metrics]
// https://komarev.com/ghpvc/?username=JonasPammer&style=flat-square
image:https://hit.yhype.me/github/profile?user_id=32995541[.,title="Do not worry weary traveller - I am but a simple counter that can only track hits, not visitors. I am being proxied through GitHub to keep your identity safe."]

// keep at bottom 😉
[[pinned]]
== Pinned Repositories / Recent Contributions
// (see below)
