---
name: Metrics
"on":
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "chore: update metrics [skip ci]"

          # Options
          base: activity, metadata
          config_timezone: Europe/Vienna
          plugin_stars: true
          # TODO self host wakatime?
          #  https://github.com/muety/wakapi
          #  Found out about this thanks to https://github.com/lowlighter/metrics/blob/master/source/plugins/wakatime/README.md
#          plugin_wakatime: true
#          plugin_wakatime_url: https://wakatime.com
#          plugin_wakatime_user: JonasPammer
