name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "chore: update metrics [Skip GitHub Action] [skip pre-commit.ci]"

          # Options
          base: activity, metadata
          config_timezone: Europe/Vienna
          plugin_stars: yes
          # TODO self host wakatime?
          #  https://github.com/muety/wakapi
          #  Found out about this thanks to https://github.com/lowlighter/metrics/blob/master/source/plugins/wakatime/README.md
#          plugin_wakatime: yes
#          plugin_wakatime_url: https://wakatime.com
#          plugin_wakatime_user: JonasPammer
