---
name: Metrics
"on":
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]
    # don't bloat too much. manual dispatch still possible if really wanted
    paths:
      - ".github/workflows/metrics.yml"
      - "github-metrics.svg"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "chore: update metrics [skip ci]"

          # configure base plugin:
          base: activity, metadata
          # configure rendering options:
          config_timezone: Europe/Vienna
          config_order: stars, wakatime, base.activity, base.metadata

          # enable/configure other plugins:
          plugin_stars: true
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
